<html>
<head>
	<title>File manager</title>
	<link type="text/css" rel="stylesheet" href="css/layout.css" />
</head>
<body>
	<div id="header">
		<ul>
			<li><a href="" id="create-folder" class="new-folder">Create folder</a></li>
			<li><a href="" id="upload-file" class="upload">Upload</a></li>
			<li><a href="" id="refresh" class="refresh">Refresh</a></li>
		</ul>
	</div>
	<div id="content">
		<div id="filelist" class="thumbnail">
			
		</div>
	</div>
	<div id="footer">
	</div>
	
	<script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="js/jquery.lazyload.js"></script>
	<script type="text/javascript" src="js/json2.js"></script>
	<script type="text/javascript" src="js/jquery.jsonrpc.js"></script>
	<script type="text/javascript" src="js/filesystem.js"></script>
	<script type="text/javascript" src="js/jquery.initialization.js"></script>
</body>
</html>